server:
  port: 8080
spring:
  application:
    name: microservice-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/configtest/config              # 配置Git仓库的地址
          username: configtest                                   # Git仓库的账号
          password: test123456                                   # Git仓库的密码